# This action is ran manually or via the dedicated `workflow` API of GitHub.
#
# The action receives as input the name of the GitHub repository that
# holds the policy, plus the tag associate with the release event of
# that policy.
#
# The action downloads the `hub.json` file from the repository mentioned
# by the input variables.
#
# The action then replaces the special `__TAG__` string inside of the
# `hub.json` file with the value of the `tag` it received at invocation
# time.
#
# Finally, the action creates a PR against this repository with the
# changes done to the file.

name: Update policy data

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Name of the repository that contains the policy (e.g.: kubewarden/psp-apparmor)"
        required: true
      tag:
        description: "Tag identifying policy release"
        required: true

jobs:
  update-policy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: fetch policy definition
        run: |
          export OUTPUT=$(echo ${{ github.event.inputs.repository }} | sed -e "s|/|:|")
          curl https://raw.githubusercontent.com/${{ github.event.inputs.repository }}/${{ github.event.inputs.tag }}/hub.json | sed -e "s|__TAG__|${{ github.event.inputs.tag }}|g" > web/src/data/${OUTPUT}.json

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Update policy ${{ github.event.inputs.repository}} to release ${{ github.event.inputs.tag }}'
          branch: 'update-${{ github.event.inputs.repository }}'
          delete-branch: true
          title: 'Track new release of policy ${{ github.event.inputs.repository }}'
          body: |
            Update data source for policy `${{ github.event.inputs.repository }}` to track release `${{ github.event.inputs.tag }}`.

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

      - name: Check PR outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

